CREATE DATABASE IF NOT EXISTS blog;

USE blog;

CREATE table IF NOT EXISTS posts (
    id INT AUTO_INCREMENT PRIMARY KEY,
    userId INT NOT NULL,
    title VARCHAR(255) NOT NULL,
    body TEXT
);

CREATE table IF NOT EXISTS comments (
    id INT AUTO_INCREMENT PRIMARY KEY,
    postId INT NOT NULL,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    body TEXT NOT NULL,
    FOREIGN KEY(postId) REFERENCES posts(id) ON UPDATE CASCADE ON DELETE CASCADE
);